name: windmill_general_trading
description: Windmill General Trading Mobile Application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bottom_navy_bar: ^6.0.0
  carousel_slider: ^4.0.0
  cloud_firestore: null
  cupertino_icons: ^1.0.2
  flutter_html: ^2.2.1
  dio: ^4.0.1
  async: ^2.8.2
  firebase_core: null
  firebase_messaging: null

  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_login_facebook: null
  font_awesome: ^5.10.1
  font_awesome_flutter: ^9.2.0
  get_storage: ^2.0.3
  google_fonts: ^2.1.0
  google_sign_in: null
  intl: ^0.17.0
  modal_bottom_sheet: ^2.0.0
  shared_preferences: null
  top_snackbar_flutter: ^1.0.1
  location: ^4.2.0
  geocoding: ^2.0.4
  google_maps_flutter: ^2.1.3
  url_launcher: ^6.0.10
  webview_flutter: ^2.0.4
  badges: ^2.0.2
  provider: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/application_icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/Montserrat/
    - assets/fonts/Poppins/
